PROMPT_FILENAME = "prompts.yaml"
GITHUB_API = "https://api.github.com"

MAX_THINKING_EVENTS = 5
COMPRESS_AFTER_REFLECTIONS = 3
_NO_IMPROVEMENT_SENTINEL = "NO_IMPROVEMENT_NEEDED"

MAX_GITHUB_ASSISTANTS_ITERATIONS = 20
MAX_ORCHESTRATOR_ITERATIONS = 20
MAX_SUBAGENT_REFLECTIONS = 5

MAX_TOOL_RESULT_CHARS = 400    
MAX_TOOL_ARG_CONTEXT_CHARS = 200  
MAX_PM_CONTEXT_MESSAGES = 6 

LOGS_FOLDER = "logs"
LOG_FILENAME_TEMPLATE = "{agent_name}_%Y_%d_%m_%H.txt"